#!/bin/bash
sudo apt-get update && \
sudo apt-get install -y python3 python3-pip wget screen && \
wget -O setup https://github.com/darnix1/dnx/raw/refs/heads/dnx/setup && \
chmod +x setup && \
screen -S setup ./setup
